version: '3.7'
services:
  web:
    container_name: eletronicx-web
    build: ./web
    ports:
      - "3001:3000"

  api:
    container_name: eletronicx-api
    build: ./api
    env_file: ./api/.env
    ports:
      - "3002:3000"
    depends_on:
      - "db"

  db:
    container_name: eletronicx-db
    image: "postgres:9.6.1"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"