version: '3.7'
services:
  web:
    container_name: eletronicx-web
    image: node:12-alpine
    working_dir: /web
    # env_file:
    #   - ./web/.env
    volumes:
      - ./web:/web
    expose:
      - "3000"
    ports:
      - "3001:3000"
    command: yarn start

  api:
    container_name: eletronicx-api
    image: node:12-alpine
    working_dir: /api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
    expose:
      - "3000"
    ports:
      - "3002:3000"
    command: yarn start
    depends_on:
      - "db"

  db:
    container_name: eletronicx-db
    image: "postgres:9.6.1"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"